### ISSUE TITLE
Password overriding

### ISSUE THREAD

**Issue by Faelivrinx** [rwinch/spring-security5-reactive-parts#2]
It looks like that method just override password. So after the first login it is not possible to log in again.

```
private Mono<User> updatePassword(Authentication authentication) {
		return this.users.findByEmail(authentication.getName())
				.publishOn(Schedulers.parallel()).doOnSuccess(u -> u.setPassword(
						this.encoder.encode(authentication.getCredentials().toString())))
				.flatMap(this.users::save);
}
```

How to fix it to work properly?

**Comment by mike2ykme** [comment]
I'm not sure if this explains what you're asking. But the Spring talk associated with this goes over this section: https://youtu.be/EDO1zlyFq6I?t=39m10s

You'll probably need to rewind a little bit to get more context but that's around when he explains the code is used for migrating a user password to a new format.

**Comment by Faelivrinx** [comment]
Yeah, I'm know what exactly that method do but I thought is here something wrong with it.

Now see I had made mistake in authenticate with passing a bad Authentication object to the updatePassword method. 

Before:


```java
@Override
public Mono<Authentication> authenticate(Authentication authentication) {
	return this.delegate.authenticate(authentication)
			.delayUntil(this::updatePassword);
	}
```

Now:
``` java
@Override
public Mono<Authentication> authenticate(Authentication authentication) {
	return this.delegate.authenticate(authentication)
			.delayUntil(a -> updatePassword(authentication));
}
```



Now everything works correctly 👍  
Thank you for the answer :)
